spring.application.name=sho8lanaTech-api

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.channel.id=${TELEGRAM_CHANNEL_ID}
telegram.community.id=${TELEGRAM_COMMUNITY_ID}

gemini.api.key=${GEMINI_API_KEY}
cohere.api.key=${COHERE_API_KEY}

upply.email=${UPPLY_EMAIL}
upply.password=${UPPLY_PASSWORD}

resend.api.key=${RESEND_API_KEY}
